# Generated by Django 5.1 on 2025-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
